default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  # schema_search_path: public,extensions

development:
  <<: *default
  database: spp_icici_api_dev
  username: icici_user
  password: admin

production:
  <<: *default
  database: spp_icici_api
  username: icici_user
  password: admin

test: &test
  <<: *default
  database: spp_icici_api_dev
  username: icici_user
  password: admin

ci: &ci
  adapter: postgresql
  host: db
  database: spp_icici_api_dev
  username: postgres
  password:
  pool: 5
  # schema_search_path: public,extensions


cucumber:
  <<: *test